# Generated by Django 3.0.3 on 2020-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='large_heading_text',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_2',
            new_name='cover_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='small_heading_text',
            new_name='l_heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='large_heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='small_heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_1',
        ),
        migrations.AddField(
            model_name='post',
            name='l_heading_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes_name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='s_heading',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='s_heading_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('News', 'News'), ('Sports', 'Sports')], default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_1',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
