# Generated by Django 3.0.3 on 2020-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200424_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quotes_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('VueJs', 'VueJs'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Machine learning', 'Machine learning'), ('JavaScript', 'JavaScript'), ('Jquery', 'Jquery'), ('Mongo DB', 'Mongo DB'), ('MySQL', 'MySQL')], default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
